feat: migrate namespace to TIM
terraform-ibm-modules/terraform-ibm-namespace pull request #2
Opened 2024-02-05 13:11 UTC by iamar7

### Description
Migration of namspace module to public

https://github.ibm.com/GoldenEye/issues/issues/6992
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [x] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-05 13:11 UTC, iamar7 commented
/run pipeline

2024-02-05 13:22 UTC, iamar7 commented
/run pipeline

2024-02-05 13:43 UTC, iamar7 commented
/run pipeline

2024-02-06 09:38 UTC, iamar7 commented
/run pipeline

2024-02-06 11:06 UTC, ocofaigh requested changes
a few small comments

2024-02-06 11:06 UTC, ocofaigh commented on README.md
> +# Replace "main" with a GIT release version to lock into a specific release
remove this comment

2024-02-06 11:06 UTC, ocofaigh commented on README.md
> +  source            = "terraform-ibm-modules/namespace-module/ibm"
repo was renamed, so update this

2024-02-06 11:06 UTC, ocofaigh commented on examples/basic/README.md
> +# Basic Example
Basic Example -> Basic example

2024-02-06 11:06 UTC, ocofaigh commented on examples/basic/main.tf
> +  source = "git::https://github.com/terraform-ibm-modules/terraform-ibm-resource-group.git?ref=v1.1.4"
please use `terraform-ibm-modules/resource-group/ibm`

2024-02-06 20:59 UTC, iamar7 commented
/run pipeline

2024-02-08 12:27 UTC, ocofaigh requested changes
just 1 comment to update topics

2024-02-08 12:27 UTC, ocofaigh commented on .github/settings.yml
>    topics: terraform, ibm-cloud, terraform-module
please add these topics too: core-team, supported, graduated, namspace, project, kubernetes, openshift

2024-02-08 13:40 UTC, iamar7 commented
/run pipeline

2024-02-08 13:46 UTC, iamar7 commented on .github/settings.yml
>    topics: terraform, ibm-cloud, terraform-module
Updated the topics.

2024-02-08 14:28 UTC, ocofaigh approved these changes

2024-02-08 14:43 UTC, merged

2024-02-08 14:44 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-namespace/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: